// GENERATED by scripts/gen_extension_rules.py from
// byoai.integrations.shield. Do not edit; re-run the script.
//
// Page world, loaded before content.js: the rules content.js uses to
// replace personal details before a message leaves the browser.
(function () {
  'use strict'
  if (window.__shieldRules) return
  const rules = {
    "pii": [
      [
        "emails",
        "[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}",
        "i"
      ],
      [
        "cards",
        "\\b4[0-9]{12}(?:[0-9]{3})?\\b|\\b(5[1-5][0-9]{14})\\b",
        ""
      ],
      [
        "wallets",
        "\\b0x[a-fA-F0-9]{40}\\b|\\bbc1[a-z0-9]{25,}\\b",
        ""
      ],
      [
        "phone_numbers",
        "\\b(?:\\+?1[-. ]?)?\\(?\\d{3}\\)?[-. ]\\d{3}[-. ]\\d{4}\\b",
        ""
      ],
      [
        "ssn_like",
        "\\b\\d{3}-\\d{2}-\\d{4}\\b",
        ""
      ],
      [
        "api_keys",
        "\\bsk-[a-zA-Z0-9]{16,}\\b|\\bBearer\\s+[A-Za-z0-9._-]{20,}\\b",
        ""
      ],
      [
        "password_said",
        "\\b(password|passphrase|credential)\\b",
        "i"
      ]
    ],
    "high": [
      [
        "executable_masquerade",
        "\\b[\\w.-]+\\.(exe|scr|bat|cmd|dmg|msi|sh)\\b",
        "i"
      ],
      [
        "credential_block",
        "\\b(password|secret|api[_ ]?key)\\s*[:=]",
        "i"
      ]
    ],
    "agent": [
      [
        "tool_intent",
        "\\b(execute|execute_stream|tool_use|deploy|refund|wire ?transfer|send (the |my )?money|draft_email)\\b",
        "i"
      ]
    ],
    "redact": {
      "emails": "[redacted-email]",
      "cards": "[redacted-card]",
      "wallets": "[redacted-wallet]",
      "phone_numbers": "[redacted-number]",
      "ssn_like": "[redacted-ssn]",
      "api_keys": "[redacted-token]"
    },
    "covered_apps": [
      "claude",
      "chatgpt"
    ]
  }
  Object.defineProperty(window, '__shieldRules', { value: Object.freeze(rules) })
})()
