// GENERATED by scripts/gen_extension_rules.py from sites.json.
// Do not edit; change sites.json and re-run the script.
//
// Where each app's message box, send button and file input are: the input
// gate's defaults. It falls back to generic selectors when these miss.
(function () {
  'use strict'
  if (window.__shieldSites) return
  const sites = {
    "sites": [
      {
        "app": "claude",
        "hosts": [
          "claude.ai"
        ],
        "compose": [
          "div[contenteditable=\"true\"][aria-label*=\"prompt\" i]",
          "div.ProseMirror[contenteditable=\"true\"]"
        ],
        "send": [
          "button[aria-label=\"Send message\"]",
          "button[aria-label*=\"send\" i]"
        ],
        "chat_paths": [
          "/chat_conversations/"
        ],
        "upload": [
          "input[type=\"file\"]"
        ]
      },
      {
        "app": "chatgpt",
        "hosts": [
          "chatgpt.com",
          "chat.openai.com"
        ],
        "compose": [
          "#prompt-textarea"
        ],
        "send": [
          "button[data-testid=\"send-button\"]"
        ],
        "chat_paths": [
          "/backend-api/conversation",
          "/backend-api/f/conversation"
        ],
        "upload": [
          "input[type=\"file\"]"
        ]
      },
      {
        "app": "gemini",
        "hosts": [
          "gemini.google.com"
        ],
        "compose": [
          "rich-textarea .ql-editor",
          "div[contenteditable=\"true\"][role=\"textbox\"]"
        ],
        "send": [
          "button[aria-label*=\"send\" i]"
        ],
        "chat_paths": [],
        "upload": [
          "input[type=\"file\"]"
        ]
      },
      {
        "app": "copilot",
        "hosts": [
          "copilot.microsoft.com"
        ],
        "compose": [
          "textarea#userInput",
          "textarea[data-testid=\"composer-input\"]"
        ],
        "send": [
          "button[data-testid=\"submit-button\"]",
          "button[aria-label*=\"submit\" i]"
        ],
        "chat_paths": [],
        "upload": [
          "input[type=\"file\"]"
        ]
      }
    ]
  }
  Object.defineProperty(window, '__shieldSites', { value: Object.freeze(sites) })
})()
