"""Write the browser extension's copy of Shield's rules: shield-rules.js.

    python scripts/gen_extension_rules.py

The extension replaces personal details in the page, before a message leaves
the browser, so it needs the same patterns the desktop proxy uses. They are
generated from ``byoai.integrations.shield`` rather than kept by hand, so the
two can't drift: ``tests/integrations/test_shield.py`` fails if the file on
disk is not what this script would write.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from byoai.integrations.shield import (
    AGENT_RULES,
    COVERED_APPS,
    HIGH_RULES,
    PII_RULES,
    RULE_REDACT,
)

TARGET = (Path(__file__).resolve().parent.parent / "src" / "byoai"
          / "browser_extension" / "shield-rules.js")


def _js_rule(name: str, pattern: re.Pattern) -> list[str]:
    """[name, source, flags] for ``new RegExp(source, flags)``. JavaScript has
    no leading ``(?i)``, so that becomes the ``i`` flag."""
    source, flags = pattern.pattern, ""
    if source.startswith("(?i)"):
        source = source[4:]
        flags = "i"
    if pattern.flags & re.I:
        flags = "i"
    # Groups JavaScript also reads: (?:  (?=  (?!  (?<=  (?<!  — anything else
    # after an unescaped "(?" (inline flags, named groups) must be rewritten.
    if re.search(r"(?<!\\)\(\?(?![:=!]|<[=!])", source):
        raise ValueError(f"rule {name!r} uses Python-only group syntax")
    return [name, source, flags]


def render() -> str:
    rules = {
        "pii": [_js_rule(n, p) for n, p in PII_RULES],
        "high": [_js_rule(n, p) for n, p in HIGH_RULES],
        "agent": [_js_rule(n, p) for n, p in AGENT_RULES],
        "redact": RULE_REDACT,
        "covered_apps": list(COVERED_APPS),
    }
    body = json.dumps(rules, indent=2)
    return (
        "// GENERATED by scripts/gen_extension_rules.py from\n"
        "// byoai.integrations.shield. Do not edit; re-run the script.\n"
        "//\n"
        "// Page world, loaded before content.js: the rules content.js uses to\n"
        "// replace personal details before a message leaves the browser.\n"
        "(function () {\n"
        "  'use strict'\n"
        "  if (window.__shieldRules) return\n"
        f"  const rules = {body.replace(chr(10), chr(10) + '  ')}\n"
        "  Object.defineProperty(window, '__shieldRules', { value: Object.freeze(rules) })\n"
        "})()\n"
    )


def main() -> None:
    TARGET.write_text(render())
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
