"""Write the browser extension's copy of Shield's rules: shield-rules.js.

    python scripts/gen_extension_rules.py

The extension replaces personal details in the page, before a message leaves
the browser, so it needs the same patterns the desktop proxy uses. They are
generated from ``byoai.integrations.shield`` rather than kept by hand, so the
two can't drift: ``tests/integrations/test_shield.py`` fails if the file on
disk is not what this script would write.
"""
from __future__ import annotations

import json
from pathlib import Path

from byoai.integrations.shield import extension_rules, rules_version_of

TARGET = (Path(__file__).resolve().parent.parent / "src" / "byoai"
          / "browser_extension" / "shield-rules.js")


def render() -> str:
    rules = extension_rules()
    # The version of the rules a file row names: a hash of everything above,
    # computed the same way in byoai.integrations.shield (RULES_VERSION).
    rules = {**rules, "rules_version": rules_version_of(rules)}
    body = json.dumps(rules, indent=2)
    return (
        "// GENERATED by scripts/gen_extension_rules.py from\n"
        "// byoai.integrations.shield. Do not edit; re-run the script.\n"
        "//\n"
        "// Page world, loaded before content.js: the rules content.js uses to\n"
        "// replace personal details before a message leaves the browser.\n"
        "(function () {\n"
        "  'use strict'\n"
        "  if (window.__shieldRules) return\n"
        f"  const rules = {body.replace(chr(10), chr(10) + '  ')}\n"
        "  Object.defineProperty(window, '__shieldRules', { value: Object.freeze(rules) })\n"
        "})()\n"
    )


def main() -> None:
    TARGET.write_text(render())
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
