/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShieldRouteImport } from './routes/shield'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as ConsoleTenantRouteImport } from './routes/console.$tenant'
import { Route as ConsoleTenantIndexRouteImport } from './routes/console.$tenant.index'
import { Route as ConsoleTenantSplatRouteImport } from './routes/console.$tenant.$'
import { Route as ConsoleTenantEvidenceRouteImport } from './routes/console.$tenant.evidence'
import { Route as ConsoleTenantFleetRouteImport } from './routes/console.$tenant.fleet'
import { Route as ConsoleTenantMandateRouteImport } from './routes/console.$tenant.mandate'
import { Route as ConsoleTenantShieldRouteImport } from './routes/console.$tenant.shield'
import { Route as ConsoleTenantShieldServerRouteImport } from './routes/console.$tenant.shield-server'
import { Route as ConsoleTenantEvidenceFindingsRouteImport } from './routes/console.$tenant.evidence.findings'
import { Route as ConsoleTenantFleetIndexRouteImport } from './routes/console.$tenant.fleet.index'
import { Route as ConsoleTenantFleetCoverageRouteImport } from './routes/console.$tenant.fleet.coverage'
import { Route as ConsoleTenantFleetDevicesRouteImport } from './routes/console.$tenant.fleet.devices'
import { Route as ConsoleTenantMandateVerdictsRouteImport } from './routes/console.$tenant.mandate.verdicts'
import { Route as ConsoleTenantShieldServerDevicesRouteImport } from './routes/console.$tenant.shield-server.devices'
import { Route as ConsoleTenantShieldServerEnrolRouteImport } from './routes/console.$tenant.shield-server.enrol'
import { Route as ConsoleTenantShieldServerPolicyRouteImport } from './routes/console.$tenant.shield-server.policy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShieldRoute = ShieldRouteImport.update({
  id: '/shield',
  path: '/shield',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/console/',
  path: '/console/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleTenantRoute = ConsoleTenantRouteImport.update({
  id: '/console/$tenant',
  path: '/console/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleTenantIndexRoute = ConsoleTenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleTenantRoute,
} as any)
const ConsoleTenantSplatRoute = ConsoleTenantSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ConsoleTenantRoute,
} as any)
const ConsoleTenantEvidenceRoute = ConsoleTenantEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => ConsoleTenantRoute,
} as any)
const ConsoleTenantFleetRoute = ConsoleTenantFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => ConsoleTenantRoute,
} as any)
const ConsoleTenantMandateRoute = ConsoleTenantMandateRouteImport.update({
  id: '/mandate',
  path: '/mandate',
  getParentRoute: () => ConsoleTenantRoute,
} as any)
const ConsoleTenantShieldRoute = ConsoleTenantShieldRouteImport.update({
  id: '/shield',
  path: '/shield',
  getParentRoute: () => ConsoleTenantRoute,
} as any)
const ConsoleTenantShieldServerRoute =
  ConsoleTenantShieldServerRouteImport.update({
    id: '/shield-server',
    path: '/shield-server',
    getParentRoute: () => ConsoleTenantRoute,
  } as any)
const ConsoleTenantEvidenceFindingsRoute =
  ConsoleTenantEvidenceFindingsRouteImport.update({
    id: '/findings',
    path: '/findings',
    getParentRoute: () => ConsoleTenantEvidenceRoute,
  } as any)
const ConsoleTenantFleetIndexRoute = ConsoleTenantFleetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleTenantFleetRoute,
} as any)
const ConsoleTenantFleetCoverageRoute =
  ConsoleTenantFleetCoverageRouteImport.update({
    id: '/coverage',
    path: '/coverage',
    getParentRoute: () => ConsoleTenantFleetRoute,
  } as any)
const ConsoleTenantFleetDevicesRoute =
  ConsoleTenantFleetDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => ConsoleTenantFleetRoute,
  } as any)
const ConsoleTenantMandateVerdictsRoute =
  ConsoleTenantMandateVerdictsRouteImport.update({
    id: '/verdicts',
    path: '/verdicts',
    getParentRoute: () => ConsoleTenantMandateRoute,
  } as any)
const ConsoleTenantShieldServerDevicesRoute =
  ConsoleTenantShieldServerDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => ConsoleTenantShieldServerRoute,
  } as any)
const ConsoleTenantShieldServerEnrolRoute =
  ConsoleTenantShieldServerEnrolRouteImport.update({
    id: '/enrol',
    path: '/enrol',
    getParentRoute: () => ConsoleTenantShieldServerRoute,
  } as any)
const ConsoleTenantShieldServerPolicyRoute =
  ConsoleTenantShieldServerPolicyRouteImport.update({
    id: '/policy',
    path: '/policy',
    getParentRoute: () => ConsoleTenantShieldServerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shield': typeof ShieldRoute
  '/console/$tenant': typeof ConsoleTenantRouteWithChildren
  '/console/': typeof ConsoleIndexRoute
  '/console/$tenant/$': typeof ConsoleTenantSplatRoute
  '/console/$tenant/evidence': typeof ConsoleTenantEvidenceRouteWithChildren
  '/console/$tenant/fleet': typeof ConsoleTenantFleetRouteWithChildren
  '/console/$tenant/mandate': typeof ConsoleTenantMandateRouteWithChildren
  '/console/$tenant/shield': typeof ConsoleTenantShieldRoute
  '/console/$tenant/shield-server': typeof ConsoleTenantShieldServerRouteWithChildren
  '/console/$tenant/': typeof ConsoleTenantIndexRoute
  '/console/$tenant/evidence/findings': typeof ConsoleTenantEvidenceFindingsRoute
  '/console/$tenant/fleet/coverage': typeof ConsoleTenantFleetCoverageRoute
  '/console/$tenant/fleet/devices': typeof ConsoleTenantFleetDevicesRoute
  '/console/$tenant/mandate/verdicts': typeof ConsoleTenantMandateVerdictsRoute
  '/console/$tenant/shield-server/devices': typeof ConsoleTenantShieldServerDevicesRoute
  '/console/$tenant/shield-server/enrol': typeof ConsoleTenantShieldServerEnrolRoute
  '/console/$tenant/shield-server/policy': typeof ConsoleTenantShieldServerPolicyRoute
  '/console/$tenant/fleet/': typeof ConsoleTenantFleetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shield': typeof ShieldRoute
  '/console': typeof ConsoleIndexRoute
  '/console/$tenant/$': typeof ConsoleTenantSplatRoute
  '/console/$tenant/evidence': typeof ConsoleTenantEvidenceRouteWithChildren
  '/console/$tenant/mandate': typeof ConsoleTenantMandateRouteWithChildren
  '/console/$tenant/shield': typeof ConsoleTenantShieldRoute
  '/console/$tenant/shield-server': typeof ConsoleTenantShieldServerRouteWithChildren
  '/console/$tenant': typeof ConsoleTenantIndexRoute
  '/console/$tenant/evidence/findings': typeof ConsoleTenantEvidenceFindingsRoute
  '/console/$tenant/fleet/coverage': typeof ConsoleTenantFleetCoverageRoute
  '/console/$tenant/fleet/devices': typeof ConsoleTenantFleetDevicesRoute
  '/console/$tenant/mandate/verdicts': typeof ConsoleTenantMandateVerdictsRoute
  '/console/$tenant/shield-server/devices': typeof ConsoleTenantShieldServerDevicesRoute
  '/console/$tenant/shield-server/enrol': typeof ConsoleTenantShieldServerEnrolRoute
  '/console/$tenant/shield-server/policy': typeof ConsoleTenantShieldServerPolicyRoute
  '/console/$tenant/fleet': typeof ConsoleTenantFleetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shield': typeof ShieldRoute
  '/console/$tenant': typeof ConsoleTenantRouteWithChildren
  '/console/': typeof ConsoleIndexRoute
  '/console/$tenant/$': typeof ConsoleTenantSplatRoute
  '/console/$tenant/evidence': typeof ConsoleTenantEvidenceRouteWithChildren
  '/console/$tenant/fleet': typeof ConsoleTenantFleetRouteWithChildren
  '/console/$tenant/mandate': typeof ConsoleTenantMandateRouteWithChildren
  '/console/$tenant/shield': typeof ConsoleTenantShieldRoute
  '/console/$tenant/shield-server': typeof ConsoleTenantShieldServerRouteWithChildren
  '/console/$tenant/': typeof ConsoleTenantIndexRoute
  '/console/$tenant/evidence/findings': typeof ConsoleTenantEvidenceFindingsRoute
  '/console/$tenant/fleet/coverage': typeof ConsoleTenantFleetCoverageRoute
  '/console/$tenant/fleet/devices': typeof ConsoleTenantFleetDevicesRoute
  '/console/$tenant/mandate/verdicts': typeof ConsoleTenantMandateVerdictsRoute
  '/console/$tenant/shield-server/devices': typeof ConsoleTenantShieldServerDevicesRoute
  '/console/$tenant/shield-server/enrol': typeof ConsoleTenantShieldServerEnrolRoute
  '/console/$tenant/shield-server/policy': typeof ConsoleTenantShieldServerPolicyRoute
  '/console/$tenant/fleet/': typeof ConsoleTenantFleetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shield'
    | '/console/$tenant'
    | '/console/'
    | '/console/$tenant/$'
    | '/console/$tenant/evidence'
    | '/console/$tenant/fleet'
    | '/console/$tenant/mandate'
    | '/console/$tenant/shield'
    | '/console/$tenant/shield-server'
    | '/console/$tenant/'
    | '/console/$tenant/evidence/findings'
    | '/console/$tenant/fleet/coverage'
    | '/console/$tenant/fleet/devices'
    | '/console/$tenant/mandate/verdicts'
    | '/console/$tenant/shield-server/devices'
    | '/console/$tenant/shield-server/enrol'
    | '/console/$tenant/shield-server/policy'
    | '/console/$tenant/fleet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shield'
    | '/console'
    | '/console/$tenant/$'
    | '/console/$tenant/evidence'
    | '/console/$tenant/mandate'
    | '/console/$tenant/shield'
    | '/console/$tenant/shield-server'
    | '/console/$tenant'
    | '/console/$tenant/evidence/findings'
    | '/console/$tenant/fleet/coverage'
    | '/console/$tenant/fleet/devices'
    | '/console/$tenant/mandate/verdicts'
    | '/console/$tenant/shield-server/devices'
    | '/console/$tenant/shield-server/enrol'
    | '/console/$tenant/shield-server/policy'
    | '/console/$tenant/fleet'
  id:
    | '__root__'
    | '/'
    | '/shield'
    | '/console/$tenant'
    | '/console/'
    | '/console/$tenant/$'
    | '/console/$tenant/evidence'
    | '/console/$tenant/fleet'
    | '/console/$tenant/mandate'
    | '/console/$tenant/shield'
    | '/console/$tenant/shield-server'
    | '/console/$tenant/'
    | '/console/$tenant/evidence/findings'
    | '/console/$tenant/fleet/coverage'
    | '/console/$tenant/fleet/devices'
    | '/console/$tenant/mandate/verdicts'
    | '/console/$tenant/shield-server/devices'
    | '/console/$tenant/shield-server/enrol'
    | '/console/$tenant/shield-server/policy'
    | '/console/$tenant/fleet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShieldRoute: typeof ShieldRoute
  ConsoleTenantRoute: typeof ConsoleTenantRouteWithChildren
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shield': {
      id: '/shield'
      path: '/shield'
      fullPath: '/shield'
      preLoaderRoute: typeof ShieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/console'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/$tenant': {
      id: '/console/$tenant'
      path: '/console/$tenant'
      fullPath: '/console/$tenant'
      preLoaderRoute: typeof ConsoleTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/$tenant/': {
      id: '/console/$tenant/'
      path: '/'
      fullPath: '/console/$tenant/'
      preLoaderRoute: typeof ConsoleTenantIndexRouteImport
      parentRoute: typeof ConsoleTenantRoute
    }
    '/console/$tenant/$': {
      id: '/console/$tenant/$'
      path: '/$'
      fullPath: '/console/$tenant/$'
      preLoaderRoute: typeof ConsoleTenantSplatRouteImport
      parentRoute: typeof ConsoleTenantRoute
    }
    '/console/$tenant/evidence': {
      id: '/console/$tenant/evidence'
      path: '/evidence'
      fullPath: '/console/$tenant/evidence'
      preLoaderRoute: typeof ConsoleTenantEvidenceRouteImport
      parentRoute: typeof ConsoleTenantRoute
    }
    '/console/$tenant/fleet': {
      id: '/console/$tenant/fleet'
      path: '/fleet'
      fullPath: '/console/$tenant/fleet'
      preLoaderRoute: typeof ConsoleTenantFleetRouteImport
      parentRoute: typeof ConsoleTenantRoute
    }
    '/console/$tenant/mandate': {
      id: '/console/$tenant/mandate'
      path: '/mandate'
      fullPath: '/console/$tenant/mandate'
      preLoaderRoute: typeof ConsoleTenantMandateRouteImport
      parentRoute: typeof ConsoleTenantRoute
    }
    '/console/$tenant/shield': {
      id: '/console/$tenant/shield'
      path: '/shield'
      fullPath: '/console/$tenant/shield'
      preLoaderRoute: typeof ConsoleTenantShieldRouteImport
      parentRoute: typeof ConsoleTenantRoute
    }
    '/console/$tenant/shield-server': {
      id: '/console/$tenant/shield-server'
      path: '/shield-server'
      fullPath: '/console/$tenant/shield-server'
      preLoaderRoute: typeof ConsoleTenantShieldServerRouteImport
      parentRoute: typeof ConsoleTenantRoute
    }
    '/console/$tenant/evidence/findings': {
      id: '/console/$tenant/evidence/findings'
      path: '/findings'
      fullPath: '/console/$tenant/evidence/findings'
      preLoaderRoute: typeof ConsoleTenantEvidenceFindingsRouteImport
      parentRoute: typeof ConsoleTenantEvidenceRoute
    }
    '/console/$tenant/fleet/': {
      id: '/console/$tenant/fleet/'
      path: '/'
      fullPath: '/console/$tenant/fleet/'
      preLoaderRoute: typeof ConsoleTenantFleetIndexRouteImport
      parentRoute: typeof ConsoleTenantFleetRoute
    }
    '/console/$tenant/fleet/coverage': {
      id: '/console/$tenant/fleet/coverage'
      path: '/coverage'
      fullPath: '/console/$tenant/fleet/coverage'
      preLoaderRoute: typeof ConsoleTenantFleetCoverageRouteImport
      parentRoute: typeof ConsoleTenantFleetRoute
    }
    '/console/$tenant/fleet/devices': {
      id: '/console/$tenant/fleet/devices'
      path: '/devices'
      fullPath: '/console/$tenant/fleet/devices'
      preLoaderRoute: typeof ConsoleTenantFleetDevicesRouteImport
      parentRoute: typeof ConsoleTenantFleetRoute
    }
    '/console/$tenant/mandate/verdicts': {
      id: '/console/$tenant/mandate/verdicts'
      path: '/verdicts'
      fullPath: '/console/$tenant/mandate/verdicts'
      preLoaderRoute: typeof ConsoleTenantMandateVerdictsRouteImport
      parentRoute: typeof ConsoleTenantMandateRoute
    }
    '/console/$tenant/shield-server/devices': {
      id: '/console/$tenant/shield-server/devices'
      path: '/devices'
      fullPath: '/console/$tenant/shield-server/devices'
      preLoaderRoute: typeof ConsoleTenantShieldServerDevicesRouteImport
      parentRoute: typeof ConsoleTenantShieldServerRoute
    }
    '/console/$tenant/shield-server/enrol': {
      id: '/console/$tenant/shield-server/enrol'
      path: '/enrol'
      fullPath: '/console/$tenant/shield-server/enrol'
      preLoaderRoute: typeof ConsoleTenantShieldServerEnrolRouteImport
      parentRoute: typeof ConsoleTenantShieldServerRoute
    }
    '/console/$tenant/shield-server/policy': {
      id: '/console/$tenant/shield-server/policy'
      path: '/policy'
      fullPath: '/console/$tenant/shield-server/policy'
      preLoaderRoute: typeof ConsoleTenantShieldServerPolicyRouteImport
      parentRoute: typeof ConsoleTenantShieldServerRoute
    }
  }
}

interface ConsoleTenantEvidenceRouteChildren {
  ConsoleTenantEvidenceFindingsRoute: typeof ConsoleTenantEvidenceFindingsRoute
}

const ConsoleTenantEvidenceRouteChildren: ConsoleTenantEvidenceRouteChildren = {
  ConsoleTenantEvidenceFindingsRoute: ConsoleTenantEvidenceFindingsRoute,
}

const ConsoleTenantEvidenceRouteWithChildren =
  ConsoleTenantEvidenceRoute._addFileChildren(
    ConsoleTenantEvidenceRouteChildren,
  )

interface ConsoleTenantFleetRouteChildren {
  ConsoleTenantFleetCoverageRoute: typeof ConsoleTenantFleetCoverageRoute
  ConsoleTenantFleetDevicesRoute: typeof ConsoleTenantFleetDevicesRoute
  ConsoleTenantFleetIndexRoute: typeof ConsoleTenantFleetIndexRoute
}

const ConsoleTenantFleetRouteChildren: ConsoleTenantFleetRouteChildren = {
  ConsoleTenantFleetCoverageRoute: ConsoleTenantFleetCoverageRoute,
  ConsoleTenantFleetDevicesRoute: ConsoleTenantFleetDevicesRoute,
  ConsoleTenantFleetIndexRoute: ConsoleTenantFleetIndexRoute,
}

const ConsoleTenantFleetRouteWithChildren =
  ConsoleTenantFleetRoute._addFileChildren(ConsoleTenantFleetRouteChildren)

interface ConsoleTenantMandateRouteChildren {
  ConsoleTenantMandateVerdictsRoute: typeof ConsoleTenantMandateVerdictsRoute
}

const ConsoleTenantMandateRouteChildren: ConsoleTenantMandateRouteChildren = {
  ConsoleTenantMandateVerdictsRoute: ConsoleTenantMandateVerdictsRoute,
}

const ConsoleTenantMandateRouteWithChildren =
  ConsoleTenantMandateRoute._addFileChildren(ConsoleTenantMandateRouteChildren)

interface ConsoleTenantShieldServerRouteChildren {
  ConsoleTenantShieldServerDevicesRoute: typeof ConsoleTenantShieldServerDevicesRoute
  ConsoleTenantShieldServerEnrolRoute: typeof ConsoleTenantShieldServerEnrolRoute
  ConsoleTenantShieldServerPolicyRoute: typeof ConsoleTenantShieldServerPolicyRoute
}

const ConsoleTenantShieldServerRouteChildren: ConsoleTenantShieldServerRouteChildren =
  {
    ConsoleTenantShieldServerDevicesRoute:
      ConsoleTenantShieldServerDevicesRoute,
    ConsoleTenantShieldServerEnrolRoute: ConsoleTenantShieldServerEnrolRoute,
    ConsoleTenantShieldServerPolicyRoute: ConsoleTenantShieldServerPolicyRoute,
  }

const ConsoleTenantShieldServerRouteWithChildren =
  ConsoleTenantShieldServerRoute._addFileChildren(
    ConsoleTenantShieldServerRouteChildren,
  )

interface ConsoleTenantRouteChildren {
  ConsoleTenantSplatRoute: typeof ConsoleTenantSplatRoute
  ConsoleTenantEvidenceRoute: typeof ConsoleTenantEvidenceRouteWithChildren
  ConsoleTenantFleetRoute: typeof ConsoleTenantFleetRouteWithChildren
  ConsoleTenantMandateRoute: typeof ConsoleTenantMandateRouteWithChildren
  ConsoleTenantShieldRoute: typeof ConsoleTenantShieldRoute
  ConsoleTenantShieldServerRoute: typeof ConsoleTenantShieldServerRouteWithChildren
  ConsoleTenantIndexRoute: typeof ConsoleTenantIndexRoute
}

const ConsoleTenantRouteChildren: ConsoleTenantRouteChildren = {
  ConsoleTenantSplatRoute: ConsoleTenantSplatRoute,
  ConsoleTenantEvidenceRoute: ConsoleTenantEvidenceRouteWithChildren,
  ConsoleTenantFleetRoute: ConsoleTenantFleetRouteWithChildren,
  ConsoleTenantMandateRoute: ConsoleTenantMandateRouteWithChildren,
  ConsoleTenantShieldRoute: ConsoleTenantShieldRoute,
  ConsoleTenantShieldServerRoute: ConsoleTenantShieldServerRouteWithChildren,
  ConsoleTenantIndexRoute: ConsoleTenantIndexRoute,
}

const ConsoleTenantRouteWithChildren = ConsoleTenantRoute._addFileChildren(
  ConsoleTenantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShieldRoute: ShieldRoute,
  ConsoleTenantRoute: ConsoleTenantRouteWithChildren,
  ConsoleIndexRoute: ConsoleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
