/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShieldRouteImport } from './routes/shield'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as ConsoleTenantRouteImport } from './routes/console.$tenant'
import { Route as ConsoleTenantIndexRouteImport } from './routes/console.$tenant.index'
import { Route as ConsoleTenantSplatRouteImport } from './routes/console.$tenant.$'
import { Route as ConsoleTenantFleetRouteImport } from './routes/console.$tenant.fleet'
import { Route as ConsoleTenantShieldRouteImport } from './routes/console.$tenant.shield'
import { Route as ConsoleTenantFleetIndexRouteImport } from './routes/console.$tenant.fleet.index'
import { Route as ConsoleTenantFleetCoverageRouteImport } from './routes/console.$tenant.fleet.coverage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShieldRoute = ShieldRouteImport.update({
  id: '/shield',
  path: '/shield',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/console/',
  path: '/console/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleTenantRoute = ConsoleTenantRouteImport.update({
  id: '/console/$tenant',
  path: '/console/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleTenantIndexRoute = ConsoleTenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleTenantRoute,
} as any)
const ConsoleTenantSplatRoute = ConsoleTenantSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ConsoleTenantRoute,
} as any)
const ConsoleTenantFleetRoute = ConsoleTenantFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => ConsoleTenantRoute,
} as any)
const ConsoleTenantShieldRoute = ConsoleTenantShieldRouteImport.update({
  id: '/shield',
  path: '/shield',
  getParentRoute: () => ConsoleTenantRoute,
} as any)
const ConsoleTenantFleetIndexRoute = ConsoleTenantFleetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleTenantFleetRoute,
} as any)
const ConsoleTenantFleetCoverageRoute =
  ConsoleTenantFleetCoverageRouteImport.update({
    id: '/coverage',
    path: '/coverage',
    getParentRoute: () => ConsoleTenantFleetRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shield': typeof ShieldRoute
  '/console/$tenant': typeof ConsoleTenantRouteWithChildren
  '/console/': typeof ConsoleIndexRoute
  '/console/$tenant/$': typeof ConsoleTenantSplatRoute
  '/console/$tenant/fleet': typeof ConsoleTenantFleetRouteWithChildren
  '/console/$tenant/shield': typeof ConsoleTenantShieldRoute
  '/console/$tenant/': typeof ConsoleTenantIndexRoute
  '/console/$tenant/fleet/coverage': typeof ConsoleTenantFleetCoverageRoute
  '/console/$tenant/fleet/': typeof ConsoleTenantFleetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shield': typeof ShieldRoute
  '/console': typeof ConsoleIndexRoute
  '/console/$tenant/$': typeof ConsoleTenantSplatRoute
  '/console/$tenant/shield': typeof ConsoleTenantShieldRoute
  '/console/$tenant': typeof ConsoleTenantIndexRoute
  '/console/$tenant/fleet/coverage': typeof ConsoleTenantFleetCoverageRoute
  '/console/$tenant/fleet': typeof ConsoleTenantFleetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shield': typeof ShieldRoute
  '/console/$tenant': typeof ConsoleTenantRouteWithChildren
  '/console/': typeof ConsoleIndexRoute
  '/console/$tenant/$': typeof ConsoleTenantSplatRoute
  '/console/$tenant/fleet': typeof ConsoleTenantFleetRouteWithChildren
  '/console/$tenant/shield': typeof ConsoleTenantShieldRoute
  '/console/$tenant/': typeof ConsoleTenantIndexRoute
  '/console/$tenant/fleet/coverage': typeof ConsoleTenantFleetCoverageRoute
  '/console/$tenant/fleet/': typeof ConsoleTenantFleetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shield'
    | '/console/$tenant'
    | '/console/'
    | '/console/$tenant/$'
    | '/console/$tenant/fleet'
    | '/console/$tenant/shield'
    | '/console/$tenant/'
    | '/console/$tenant/fleet/coverage'
    | '/console/$tenant/fleet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shield'
    | '/console'
    | '/console/$tenant/$'
    | '/console/$tenant/shield'
    | '/console/$tenant'
    | '/console/$tenant/fleet/coverage'
    | '/console/$tenant/fleet'
  id:
    | '__root__'
    | '/'
    | '/shield'
    | '/console/$tenant'
    | '/console/'
    | '/console/$tenant/$'
    | '/console/$tenant/fleet'
    | '/console/$tenant/shield'
    | '/console/$tenant/'
    | '/console/$tenant/fleet/coverage'
    | '/console/$tenant/fleet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShieldRoute: typeof ShieldRoute
  ConsoleTenantRoute: typeof ConsoleTenantRouteWithChildren
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shield': {
      id: '/shield'
      path: '/shield'
      fullPath: '/shield'
      preLoaderRoute: typeof ShieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/console'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/$tenant': {
      id: '/console/$tenant'
      path: '/console/$tenant'
      fullPath: '/console/$tenant'
      preLoaderRoute: typeof ConsoleTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/$tenant/': {
      id: '/console/$tenant/'
      path: '/'
      fullPath: '/console/$tenant/'
      preLoaderRoute: typeof ConsoleTenantIndexRouteImport
      parentRoute: typeof ConsoleTenantRoute
    }
    '/console/$tenant/$': {
      id: '/console/$tenant/$'
      path: '/$'
      fullPath: '/console/$tenant/$'
      preLoaderRoute: typeof ConsoleTenantSplatRouteImport
      parentRoute: typeof ConsoleTenantRoute
    }
    '/console/$tenant/fleet': {
      id: '/console/$tenant/fleet'
      path: '/fleet'
      fullPath: '/console/$tenant/fleet'
      preLoaderRoute: typeof ConsoleTenantFleetRouteImport
      parentRoute: typeof ConsoleTenantRoute
    }
    '/console/$tenant/shield': {
      id: '/console/$tenant/shield'
      path: '/shield'
      fullPath: '/console/$tenant/shield'
      preLoaderRoute: typeof ConsoleTenantShieldRouteImport
      parentRoute: typeof ConsoleTenantRoute
    }
    '/console/$tenant/fleet/': {
      id: '/console/$tenant/fleet/'
      path: '/'
      fullPath: '/console/$tenant/fleet/'
      preLoaderRoute: typeof ConsoleTenantFleetIndexRouteImport
      parentRoute: typeof ConsoleTenantFleetRoute
    }
    '/console/$tenant/fleet/coverage': {
      id: '/console/$tenant/fleet/coverage'
      path: '/coverage'
      fullPath: '/console/$tenant/fleet/coverage'
      preLoaderRoute: typeof ConsoleTenantFleetCoverageRouteImport
      parentRoute: typeof ConsoleTenantFleetRoute
    }
  }
}

interface ConsoleTenantFleetRouteChildren {
  ConsoleTenantFleetCoverageRoute: typeof ConsoleTenantFleetCoverageRoute
  ConsoleTenantFleetIndexRoute: typeof ConsoleTenantFleetIndexRoute
}

const ConsoleTenantFleetRouteChildren: ConsoleTenantFleetRouteChildren = {
  ConsoleTenantFleetCoverageRoute: ConsoleTenantFleetCoverageRoute,
  ConsoleTenantFleetIndexRoute: ConsoleTenantFleetIndexRoute,
}

const ConsoleTenantFleetRouteWithChildren =
  ConsoleTenantFleetRoute._addFileChildren(ConsoleTenantFleetRouteChildren)

interface ConsoleTenantRouteChildren {
  ConsoleTenantSplatRoute: typeof ConsoleTenantSplatRoute
  ConsoleTenantFleetRoute: typeof ConsoleTenantFleetRouteWithChildren
  ConsoleTenantShieldRoute: typeof ConsoleTenantShieldRoute
  ConsoleTenantIndexRoute: typeof ConsoleTenantIndexRoute
}

const ConsoleTenantRouteChildren: ConsoleTenantRouteChildren = {
  ConsoleTenantSplatRoute: ConsoleTenantSplatRoute,
  ConsoleTenantFleetRoute: ConsoleTenantFleetRouteWithChildren,
  ConsoleTenantShieldRoute: ConsoleTenantShieldRoute,
  ConsoleTenantIndexRoute: ConsoleTenantIndexRoute,
}

const ConsoleTenantRouteWithChildren = ConsoleTenantRoute._addFileChildren(
  ConsoleTenantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShieldRoute: ShieldRoute,
  ConsoleTenantRoute: ConsoleTenantRouteWithChildren,
  ConsoleIndexRoute: ConsoleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
